package com.ar.vgmsistemas.dto;
// Generated 24-jun-2019 12:24:44 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentosId generated by hbm2java
 */
@Embeddable
public class DocumentosId implements java.io.Serializable {

	private String idDoc;
	private char idLetra;
	private int idPtovta;

	public DocumentosId() {
	}

	public DocumentosId(String idDoc, char idLetra, int idPtovta) {
		this.idDoc = idDoc;
		this.idLetra = idLetra;
		this.idPtovta = idPtovta;
	}

	@Column(name = "id_doc", nullable = false, length = 2)
	public String getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(String idDoc) {
		this.idDoc = idDoc;
	}

	@Column(name = "id_letra", nullable = false, length = 1)
	public char getIdLetra() {
		return this.idLetra;
	}

	public void setIdLetra(char idLetra) {
		this.idLetra = idLetra;
	}

	@Column(name = "id_ptovta", nullable = false)
	public int getIdPtovta() {
		return this.idPtovta;
	}

	public void setIdPtovta(int idPtovta) {
		this.idPtovta = idPtovta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentosId))
			return false;
		DocumentosId castOther = (DocumentosId) other;

		return ((this.getIdDoc() == castOther.getIdDoc()) || (this.getIdDoc() != null && castOther.getIdDoc() != null
				&& this.getIdDoc().equals(castOther.getIdDoc()))) && (this.getIdLetra() == castOther.getIdLetra())
				&& (this.getIdPtovta() == castOther.getIdPtovta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDoc() == null ? 0 : this.getIdDoc().hashCode());
		result = 37 * result + this.getIdLetra();
		result = 37 * result + this.getIdPtovta();
		return result;
	}

}
