package com.ar.vgmsistemas.dto;
// Generated 24-jun-2019 12:24:44 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "Documentos", schema = "dbo", catalog = "JotaBePdas")
public class Documentos implements java.io.Serializable {

	private DocumentosId id;
	private Integer idNumero;
	private String deDocumento;
	private Integer nuCopias;
	private Character snVisualizar;
	private Date feDoc;
	private Integer nuLineas;
	private Integer idN1;
	private String dwFormulario;
	private String deImpresora;
	private Character snImpreAuto;
	private String deRed;
	private Integer tiAplicastock;
	private Character snCopias;
	private Integer tiAplicaStock;
	private Character snNumeraActual;
	private String idNumeraFcnc;
	private Character idNumeraTipoab;
	private Integer tiAplicaCc;
	private Integer idNumeraPtovta;
	private Integer tiAplicaIva;
	private Integer tiAplicaCaja;
	private Character snDetallaCaja;
	private Integer idTipovalorCaja;
	private Character snAutomaticaCaja;
	private Integer idValorCaja;
	private Character snNumeraAut;
	private Integer tiAplicaInfo;
	private Character snAplicaImportes;
	private Character tiDocumento;
	private Integer idImpresion;
	private String tiFiscalDefault;
	private BigDecimal prLimiteventa;
	private Character snEstadistica;
	private Character snGenerar;
	private Character snUltimoCompCli;
	private Character snReparto;
	private String idDocanulaFcnc;
	private Character idDocanulaTipoab;
	private Integer idDocanulaPtovta;
	private Integer tiBorraEn;
	private Character snControlPedido;
	private String snDocAsientoContable;
	private Integer tiAplicaCompAnticipo;
	private String snCompAnticipo;
	private String snEstados;
	private String idFcncAfip;
	private String snAutoimpresion;
	private String idGenerarFcnc;
	private String idGenerarTipoab;
	private Integer idGenerarPtovta;
	private String snAplicaDetalle;
	private Character tiBn;
	private Character snMovil;
	private String idQuiebreFcnc;
	private String idQuiebreTipoab;
	private Integer idQuiebrePtovta;
	private String snCompQuiebre;
	private Integer idCategoria2;
	private Character snPreventaWeb;
	private Integer tiDesdoble;
	private String snFacturaElectronica;
	private Integer tiAplicaFacturaElectronica;
	private String snHojadep;
	private String snTransferir;
	private Character snMovdep;
	private String snIngresoMercaderia;
	private String snPedidoWeb;
	private String snImprimirImpMovil;
	private Integer tiAplicaStockCliente;
	private String tiPedidoRentable;
	private Character snControlSubrubro;
	public static final Integer TI_DESOBLE_SUCURSAL = 3;

	public Documentos() {
	}

	public Documentos(DocumentosId id, String snPedidoWeb) {
		this.id = id;
		this.snPedidoWeb = snPedidoWeb;
	}

	public Documentos(DocumentosId id, Integer idNumero, String deDocumento, Integer nuCopias, Character snVisualizar,
			Date feDoc, Integer nuLineas, Integer idN1, String dwFormulario, String deImpresora, Character snImpreAuto,
			String deRed, Integer tiAplicastock, Character snCopias, Integer tiAplicaStock, Character snNumeraActual,
			String idNumeraFcnc, Character idNumeraTipoab, Integer tiAplicaCc, Integer idNumeraPtovta,
			Integer tiAplicaIva, Integer tiAplicaCaja, Character snDetallaCaja, Integer idTipovalorCaja,
			Character snAutomaticaCaja, Integer idValorCaja, Character snNumeraAut, Integer tiAplicaInfo,
			Character snAplicaImportes, Character tiDocumento, Integer idImpresion, String tiFiscalDefault,
			BigDecimal prLimiteventa, Character snEstadistica, Character snGenerar, Character snUltimoCompCli,
			Character snReparto, String idDocanulaFcnc, Character idDocanulaTipoab, Integer idDocanulaPtovta,
			Integer tiBorraEn, Character snControlPedido, String snDocAsientoContable, Integer tiAplicaCompAnticipo,
			String snCompAnticipo, String snEstados, String idFcncAfip, String snAutoimpresion, String idGenerarFcnc,
			String idGenerarTipoab, Integer idGenerarPtovta, String snAplicaDetalle, Character tiBn, Character snMovil,
			String idQuiebreFcnc, String idQuiebreTipoab, Integer idQuiebrePtovta, String snCompQuiebre,
			Integer idCategoria2, Character snPreventaWeb, Integer tiDesdoble, String snFacturaElectronica,
			Integer tiAplicaFacturaElectronica, String snHojadep, String snTransferir, Character snMovdep,
			String snIngresoMercaderia, String snPedidoWeb, String snImprimirImpMovil, Integer tiAplicaStockCliente,
			String tiPedidoRentable, Character snControlSubrubro) {
		this.id = id;
		this.idNumero = idNumero;
		this.deDocumento = deDocumento;
		this.nuCopias = nuCopias;
		this.snVisualizar = snVisualizar;
		this.feDoc = feDoc;
		this.nuLineas = nuLineas;
		this.idN1 = idN1;
		this.dwFormulario = dwFormulario;
		this.deImpresora = deImpresora;
		this.snImpreAuto = snImpreAuto;
		this.deRed = deRed;
		this.tiAplicastock = tiAplicastock;
		this.snCopias = snCopias;
		this.tiAplicaStock = tiAplicaStock;
		this.snNumeraActual = snNumeraActual;
		this.idNumeraFcnc = idNumeraFcnc;
		this.idNumeraTipoab = idNumeraTipoab;
		this.tiAplicaCc = tiAplicaCc;
		this.idNumeraPtovta = idNumeraPtovta;
		this.tiAplicaIva = tiAplicaIva;
		this.tiAplicaCaja = tiAplicaCaja;
		this.snDetallaCaja = snDetallaCaja;
		this.idTipovalorCaja = idTipovalorCaja;
		this.snAutomaticaCaja = snAutomaticaCaja;
		this.idValorCaja = idValorCaja;
		this.snNumeraAut = snNumeraAut;
		this.tiAplicaInfo = tiAplicaInfo;
		this.snAplicaImportes = snAplicaImportes;
		this.tiDocumento = tiDocumento;
		this.idImpresion = idImpresion;
		this.tiFiscalDefault = tiFiscalDefault;
		this.prLimiteventa = prLimiteventa;
		this.snEstadistica = snEstadistica;
		this.snGenerar = snGenerar;
		this.snUltimoCompCli = snUltimoCompCli;
		this.snReparto = snReparto;
		this.idDocanulaFcnc = idDocanulaFcnc;
		this.idDocanulaTipoab = idDocanulaTipoab;
		this.idDocanulaPtovta = idDocanulaPtovta;
		this.tiBorraEn = tiBorraEn;
		this.snControlPedido = snControlPedido;
		this.snDocAsientoContable = snDocAsientoContable;
		this.tiAplicaCompAnticipo = tiAplicaCompAnticipo;
		this.snCompAnticipo = snCompAnticipo;
		this.snEstados = snEstados;
		this.idFcncAfip = idFcncAfip;
		this.snAutoimpresion = snAutoimpresion;
		this.idGenerarFcnc = idGenerarFcnc;
		this.idGenerarTipoab = idGenerarTipoab;
		this.idGenerarPtovta = idGenerarPtovta;
		this.snAplicaDetalle = snAplicaDetalle;
		this.tiBn = tiBn;
		this.snMovil = snMovil;
		this.idQuiebreFcnc = idQuiebreFcnc;
		this.idQuiebreTipoab = idQuiebreTipoab;
		this.idQuiebrePtovta = idQuiebrePtovta;
		this.snCompQuiebre = snCompQuiebre;
		this.idCategoria2 = idCategoria2;
		this.snPreventaWeb = snPreventaWeb;
		this.tiDesdoble = tiDesdoble;
		this.snFacturaElectronica = snFacturaElectronica;
		this.tiAplicaFacturaElectronica = tiAplicaFacturaElectronica;
		this.snHojadep = snHojadep;
		this.snTransferir = snTransferir;
		this.snMovdep = snMovdep;
		this.snIngresoMercaderia = snIngresoMercaderia;
		this.snPedidoWeb = snPedidoWeb;
		this.snImprimirImpMovil = snImprimirImpMovil;
		this.tiAplicaStockCliente = tiAplicaStockCliente;
		this.tiPedidoRentable = tiPedidoRentable;
		this.snControlSubrubro = snControlSubrubro;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDoc", column = @Column(name = "id_doc", nullable = false, length = 2)),
			@AttributeOverride(name = "idLetra", column = @Column(name = "id_letra", nullable = false, length = 1)),
			@AttributeOverride(name = "idPtovta", column = @Column(name = "id_ptovta", nullable = false)) })
	public DocumentosId getId() {
		return this.id;
	}

	public void setId(DocumentosId id) {
		this.id = id;
	}

	@Column(name = "id_numero")
	public Integer getIdNumero() {
		return this.idNumero;
	}

	public void setIdNumero(Integer idNumero) {
		this.idNumero = idNumero;
	}

	@Column(name = "de_documento", length = 25)
	public String getDeDocumento() {
		return this.deDocumento;
	}

	public void setDeDocumento(String deDocumento) {
		this.deDocumento = deDocumento;
	}

	@Column(name = "nu_copias")
	public Integer getNuCopias() {
		return this.nuCopias;
	}

	public void setNuCopias(Integer nuCopias) {
		this.nuCopias = nuCopias;
	}

	@Column(name = "sn_visualizar", length = 1)
	public Character getSnVisualizar() {
		return this.snVisualizar;
	}

	public void setSnVisualizar(Character snVisualizar) {
		this.snVisualizar = snVisualizar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fe_doc", length = 23)
	public Date getFeDoc() {
		return this.feDoc;
	}

	public void setFeDoc(Date feDoc) {
		this.feDoc = feDoc;
	}

	@Column(name = "nu_lineas")
	public Integer getNuLineas() {
		return this.nuLineas;
	}

	public void setNuLineas(Integer nuLineas) {
		this.nuLineas = nuLineas;
	}

	@Column(name = "id_n1")
	public Integer getIdN1() {
		return this.idN1;
	}

	public void setIdN1(Integer idN1) {
		this.idN1 = idN1;
	}

	@Column(name = "dw_formulario", length = 50)
	public String getDwFormulario() {
		return this.dwFormulario;
	}

	public void setDwFormulario(String dwFormulario) {
		this.dwFormulario = dwFormulario;
	}

	@Column(name = "de_impresora", length = 50)
	public String getDeImpresora() {
		return this.deImpresora;
	}

	public void setDeImpresora(String deImpresora) {
		this.deImpresora = deImpresora;
	}

	@Column(name = "sn_impre_auto", length = 1)
	public Character getSnImpreAuto() {
		return this.snImpreAuto;
	}

	public void setSnImpreAuto(Character snImpreAuto) {
		this.snImpreAuto = snImpreAuto;
	}

	@Column(name = "de_red", length = 60)
	public String getDeRed() {
		return this.deRed;
	}

	public void setDeRed(String deRed) {
		this.deRed = deRed;
	}

	@Column(name = "ti_aplicastock")
	public Integer getTiAplicastock() {
		return this.tiAplicastock;
	}

	public void setTiAplicastock(Integer tiAplicastock) {
		this.tiAplicastock = tiAplicastock;
	}

	@Column(name = "sn_copias", length = 1)
	public Character getSnCopias() {
		return this.snCopias;
	}

	public void setSnCopias(Character snCopias) {
		this.snCopias = snCopias;
	}

	@Column(name = "ti_aplica_stock")
	public Integer getTiAplicaStock() {
		return this.tiAplicaStock;
	}

	public void setTiAplicaStock(Integer tiAplicaStock) {
		this.tiAplicaStock = tiAplicaStock;
	}

	@Column(name = "sn_numera_actual", length = 1)
	public Character getSnNumeraActual() {
		return this.snNumeraActual;
	}

	public void setSnNumeraActual(Character snNumeraActual) {
		this.snNumeraActual = snNumeraActual;
	}

	@Column(name = "id_numera_fcnc", length = 2)
	public String getIdNumeraFcnc() {
		return this.idNumeraFcnc;
	}

	public void setIdNumeraFcnc(String idNumeraFcnc) {
		this.idNumeraFcnc = idNumeraFcnc;
	}

	@Column(name = "id_numera_tipoab", length = 1)
	public Character getIdNumeraTipoab() {
		return this.idNumeraTipoab;
	}

	public void setIdNumeraTipoab(Character idNumeraTipoab) {
		this.idNumeraTipoab = idNumeraTipoab;
	}

	@Column(name = "ti_aplica_cc")
	public Integer getTiAplicaCc() {
		return this.tiAplicaCc;
	}

	public void setTiAplicaCc(Integer tiAplicaCc) {
		this.tiAplicaCc = tiAplicaCc;
	}

	@Column(name = "id_numera_ptovta")
	public Integer getIdNumeraPtovta() {
		return this.idNumeraPtovta;
	}

	public void setIdNumeraPtovta(Integer idNumeraPtovta) {
		this.idNumeraPtovta = idNumeraPtovta;
	}

	@Column(name = "ti_aplica_iva")
	public Integer getTiAplicaIva() {
		return this.tiAplicaIva;
	}

	public void setTiAplicaIva(Integer tiAplicaIva) {
		this.tiAplicaIva = tiAplicaIva;
	}

	@Column(name = "ti_aplica_caja")
	public Integer getTiAplicaCaja() {
		return this.tiAplicaCaja;
	}

	public void setTiAplicaCaja(Integer tiAplicaCaja) {
		this.tiAplicaCaja = tiAplicaCaja;
	}

	@Column(name = "sn_detalla_caja", length = 1)
	public Character getSnDetallaCaja() {
		return this.snDetallaCaja;
	}

	public void setSnDetallaCaja(Character snDetallaCaja) {
		this.snDetallaCaja = snDetallaCaja;
	}

	@Column(name = "id_tipovalor_caja")
	public Integer getIdTipovalorCaja() {
		return this.idTipovalorCaja;
	}

	public void setIdTipovalorCaja(Integer idTipovalorCaja) {
		this.idTipovalorCaja = idTipovalorCaja;
	}

	@Column(name = "sn_automatica_caja", length = 1)
	public Character getSnAutomaticaCaja() {
		return this.snAutomaticaCaja;
	}

	public void setSnAutomaticaCaja(Character snAutomaticaCaja) {
		this.snAutomaticaCaja = snAutomaticaCaja;
	}

	@Column(name = "id_valor_caja")
	public Integer getIdValorCaja() {
		return this.idValorCaja;
	}

	public void setIdValorCaja(Integer idValorCaja) {
		this.idValorCaja = idValorCaja;
	}

	@Column(name = "sn_numera_aut", length = 1)
	public Character getSnNumeraAut() {
		return this.snNumeraAut;
	}

	public void setSnNumeraAut(Character snNumeraAut) {
		this.snNumeraAut = snNumeraAut;
	}

	@Column(name = "ti_aplica_info")
	public Integer getTiAplicaInfo() {
		return this.tiAplicaInfo;
	}

	public void setTiAplicaInfo(Integer tiAplicaInfo) {
		this.tiAplicaInfo = tiAplicaInfo;
	}

	@Column(name = "sn_aplica_importes", length = 1)
	public Character getSnAplicaImportes() {
		return this.snAplicaImportes;
	}

	public void setSnAplicaImportes(Character snAplicaImportes) {
		this.snAplicaImportes = snAplicaImportes;
	}

	@Column(name = "ti_documento", length = 1)
	public Character getTiDocumento() {
		return this.tiDocumento;
	}

	public void setTiDocumento(Character tiDocumento) {
		this.tiDocumento = tiDocumento;
	}

	@Column(name = "id_impresion")
	public Integer getIdImpresion() {
		return this.idImpresion;
	}

	public void setIdImpresion(Integer idImpresion) {
		this.idImpresion = idImpresion;
	}

	@Column(name = "ti_fiscal_default", length = 18)
	public String getTiFiscalDefault() {
		return this.tiFiscalDefault;
	}

	public void setTiFiscalDefault(String tiFiscalDefault) {
		this.tiFiscalDefault = tiFiscalDefault;
	}

	@Column(name = "pr_limiteventa", precision = 12)
	public BigDecimal getPrLimiteventa() {
		return this.prLimiteventa;
	}

	public void setPrLimiteventa(BigDecimal prLimiteventa) {
		this.prLimiteventa = prLimiteventa;
	}

	@Column(name = "sn_estadistica", length = 1)
	public Character getSnEstadistica() {
		return this.snEstadistica;
	}

	public void setSnEstadistica(Character snEstadistica) {
		this.snEstadistica = snEstadistica;
	}

	@Column(name = "sn_generar", length = 1)
	public Character getSnGenerar() {
		return this.snGenerar;
	}

	public void setSnGenerar(Character snGenerar) {
		this.snGenerar = snGenerar;
	}

	@Column(name = "sn_ultimo_comp_cli", length = 1)
	public Character getSnUltimoCompCli() {
		return this.snUltimoCompCli;
	}

	public void setSnUltimoCompCli(Character snUltimoCompCli) {
		this.snUltimoCompCli = snUltimoCompCli;
	}

	@Column(name = "sn_reparto", length = 1)
	public Character getSnReparto() {
		return this.snReparto;
	}

	public void setSnReparto(Character snReparto) {
		this.snReparto = snReparto;
	}

	@Column(name = "id_docanula_fcnc", length = 2)
	public String getIdDocanulaFcnc() {
		return this.idDocanulaFcnc;
	}

	public void setIdDocanulaFcnc(String idDocanulaFcnc) {
		this.idDocanulaFcnc = idDocanulaFcnc;
	}

	@Column(name = "id_docanula_tipoab", length = 1)
	public Character getIdDocanulaTipoab() {
		return this.idDocanulaTipoab;
	}

	public void setIdDocanulaTipoab(Character idDocanulaTipoab) {
		this.idDocanulaTipoab = idDocanulaTipoab;
	}

	@Column(name = "id_docanula_ptovta")
	public Integer getIdDocanulaPtovta() {
		return this.idDocanulaPtovta;
	}

	public void setIdDocanulaPtovta(Integer idDocanulaPtovta) {
		this.idDocanulaPtovta = idDocanulaPtovta;
	}

	@Column(name = "ti_borra_en")
	public Integer getTiBorraEn() {
		return this.tiBorraEn;
	}

	public void setTiBorraEn(Integer tiBorraEn) {
		this.tiBorraEn = tiBorraEn;
	}

	@Column(name = "sn_control_pedido", length = 1)
	public Character getSnControlPedido() {
		return this.snControlPedido;
	}

	public void setSnControlPedido(Character snControlPedido) {
		this.snControlPedido = snControlPedido;
	}

	@Column(name = "sn_doc_asiento_contable", length = 1)
	public String getSnDocAsientoContable() {
		return this.snDocAsientoContable;
	}

	public void setSnDocAsientoContable(String snDocAsientoContable) {
		this.snDocAsientoContable = snDocAsientoContable;
	}

	@Column(name = "ti_aplica_comp_anticipo")
	public Integer getTiAplicaCompAnticipo() {
		return this.tiAplicaCompAnticipo;
	}

	public void setTiAplicaCompAnticipo(Integer tiAplicaCompAnticipo) {
		this.tiAplicaCompAnticipo = tiAplicaCompAnticipo;
	}

	@Column(name = "sn_comp_anticipo", length = 1)
	public String getSnCompAnticipo() {
		return this.snCompAnticipo;
	}

	public void setSnCompAnticipo(String snCompAnticipo) {
		this.snCompAnticipo = snCompAnticipo;
	}

	@Column(name = "sn_estados", length = 20)
	public String getSnEstados() {
		return this.snEstados;
	}

	public void setSnEstados(String snEstados) {
		this.snEstados = snEstados;
	}

	@Column(name = "id_fcnc_afip", length = 3)
	public String getIdFcncAfip() {
		return this.idFcncAfip;
	}

	public void setIdFcncAfip(String idFcncAfip) {
		this.idFcncAfip = idFcncAfip;
	}

	@Column(name = "sn_autoimpresion", length = 1)
	public String getSnAutoimpresion() {
		return this.snAutoimpresion;
	}

	public void setSnAutoimpresion(String snAutoimpresion) {
		this.snAutoimpresion = snAutoimpresion;
	}

	@Column(name = "id_generar_fcnc", length = 2)
	public String getIdGenerarFcnc() {
		return this.idGenerarFcnc;
	}

	public void setIdGenerarFcnc(String idGenerarFcnc) {
		this.idGenerarFcnc = idGenerarFcnc;
	}

	@Column(name = "id_generar_tipoab", length = 1)
	public String getIdGenerarTipoab() {
		return this.idGenerarTipoab;
	}

	public void setIdGenerarTipoab(String idGenerarTipoab) {
		this.idGenerarTipoab = idGenerarTipoab;
	}

	@Column(name = "id_generar_ptovta")
	public Integer getIdGenerarPtovta() {
		return this.idGenerarPtovta;
	}

	public void setIdGenerarPtovta(Integer idGenerarPtovta) {
		this.idGenerarPtovta = idGenerarPtovta;
	}

	@Column(name = "sn_aplica_detalle", length = 1)
	public String getSnAplicaDetalle() {
		return this.snAplicaDetalle;
	}

	public void setSnAplicaDetalle(String snAplicaDetalle) {
		this.snAplicaDetalle = snAplicaDetalle;
	}

	@Column(name = "ti_bn", length = 1)
	public Character getTiBn() {
		return this.tiBn;
	}

	public void setTiBn(Character tiBn) {
		this.tiBn = tiBn;
	}

	@Column(name = "sn_movil", length = 1)
	public Character getSnMovil() {
		return this.snMovil;
	}

	public void setSnMovil(Character snMovil) {
		this.snMovil = snMovil;
	}

	@Column(name = "id_quiebre_fcnc", length = 2)
	public String getIdQuiebreFcnc() {
		return this.idQuiebreFcnc;
	}

	public void setIdQuiebreFcnc(String idQuiebreFcnc) {
		this.idQuiebreFcnc = idQuiebreFcnc;
	}

	@Column(name = "id_quiebre_tipoab", length = 1)
	public String getIdQuiebreTipoab() {
		return this.idQuiebreTipoab;
	}

	public void setIdQuiebreTipoab(String idQuiebreTipoab) {
		this.idQuiebreTipoab = idQuiebreTipoab;
	}

	@Column(name = "id_quiebre_ptovta")
	public Integer getIdQuiebrePtovta() {
		return this.idQuiebrePtovta;
	}

	public void setIdQuiebrePtovta(Integer idQuiebrePtovta) {
		this.idQuiebrePtovta = idQuiebrePtovta;
	}

	@Column(name = "sn_comp_quiebre", length = 1)
	public String getSnCompQuiebre() {
		return this.snCompQuiebre;
	}

	public void setSnCompQuiebre(String snCompQuiebre) {
		this.snCompQuiebre = snCompQuiebre;
	}

	@Column(name = "id_categoria2")
	public Integer getIdCategoria2() {
		return this.idCategoria2;
	}

	public void setIdCategoria2(Integer idCategoria2) {
		this.idCategoria2 = idCategoria2;
	}

	@Column(name = "sn_preventa_web", length = 1)
	public Character getSnPreventaWeb() {
		return this.snPreventaWeb;
	}

	public void setSnPreventaWeb(Character snPreventaWeb) {
		this.snPreventaWeb = snPreventaWeb;
	}

	@Column(name = "ti_desdoble")
	public Integer getTiDesdoble() {
		return this.tiDesdoble;
	}

	public void setTiDesdoble(Integer tiDesdoble) {
		this.tiDesdoble = tiDesdoble;
	}

	@Column(name = "sn_factura_electronica", length = 1)
	public String getSnFacturaElectronica() {
		return this.snFacturaElectronica;
	}

	public void setSnFacturaElectronica(String snFacturaElectronica) {
		this.snFacturaElectronica = snFacturaElectronica;
	}

	@Column(name = "ti_aplica_factura_electronica")
	public Integer getTiAplicaFacturaElectronica() {
		return this.tiAplicaFacturaElectronica;
	}

	public void setTiAplicaFacturaElectronica(Integer tiAplicaFacturaElectronica) {
		this.tiAplicaFacturaElectronica = tiAplicaFacturaElectronica;
	}

	@Column(name = "sn_hojadep", length = 1)
	public String getSnHojadep() {
		return this.snHojadep;
	}

	public void setSnHojadep(String snHojadep) {
		this.snHojadep = snHojadep;
	}

	@Column(name = "sn_transferir", length = 1)
	public String getSnTransferir() {
		return this.snTransferir;
	}

	public void setSnTransferir(String snTransferir) {
		this.snTransferir = snTransferir;
	}

	@Column(name = "sn_movdep", length = 1)
	public Character getSnMovdep() {
		return this.snMovdep;
	}

	public void setSnMovdep(Character snMovdep) {
		this.snMovdep = snMovdep;
	}

	@Column(name = "sn_ingreso_mercaderia", length = 1)
	public String getSnIngresoMercaderia() {
		return this.snIngresoMercaderia;
	}

	public void setSnIngresoMercaderia(String snIngresoMercaderia) {
		this.snIngresoMercaderia = snIngresoMercaderia;
	}

	@Column(name = "sn_pedido_web", nullable = false, length = 1)
	public String getSnPedidoWeb() {
		return this.snPedidoWeb;
	}

	public void setSnPedidoWeb(String snPedidoWeb) {
		this.snPedidoWeb = snPedidoWeb;
	}

	@Column(name = "sn_imprimir_imp_movil", length = 1)
	public String getSnImprimirImpMovil() {
		return this.snImprimirImpMovil;
	}

	public void setSnImprimirImpMovil(String snImprimirImpMovil) {
		this.snImprimirImpMovil = snImprimirImpMovil;
	}

	@Column(name = "ti_aplica_stock_cliente")
	public Integer getTiAplicaStockCliente() {
		return this.tiAplicaStockCliente;
	}

	public void setTiAplicaStockCliente(Integer tiAplicaStockCliente) {
		this.tiAplicaStockCliente = tiAplicaStockCliente;
	}

	@Column(name = "ti_pedido_rentable", length = 1)
	public String getTiPedidoRentable() {
		return this.tiPedidoRentable;
	}

	public void setTiPedidoRentable(String tiPedidoRentable) {
		this.tiPedidoRentable = tiPedidoRentable;
	}

	@Column(name = "sn_control_subrubro", length = 1)
	public Character getSnControlSubrubro() {
		return this.snControlSubrubro;
	}

	public void setSnControlSubrubro(Character snControlSubrubro) {
		this.snControlSubrubro = snControlSubrubro;
	}

}
